export const CART_SAVE_SHIPPING_ADDRESS = "CART_SAVE_SHIPPING_ADDRESS";

export const SAVE_PAYMENT_METHOD = "SAVE_PAYMENT_METHOD";

export const CART_EMPTY = "CART_EMPTY";

export const CART_ADD_ITEM_FAIL = "CART_ADD_ITEM_FAI";
